version: '2'

services:

  elasticsearch:
    image: deviantony/elk-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elastic

  kibana:
    image: deviantony/elk-kibana
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  elasticsearch-importer-api:
    build: ./src/elasticsearch-import-api-docker
    ports:
      - "8088:80"
    networks:
      - elastic
    depends_on:
      - elasticsearch

networks:

  elastic:
    driver: bridge
