version: '2.1'

services:

  elasticsearch-importer-api:
    volumes:
      - "./src/elasticsearch-import-api-docker/src/elasticsearch-import-api-symfony:/var/www/project"
    env_file:
      - ./dev.env
    environment:
      - WWW_UID=1000
      - WWW_GID=1000

  dkan_apache_php:
    image: apache-php-fpm:latest
    environment:
      WWW_UID: 501
      WWW_GID: 501
    volumes:
      - ./src/dkan-opendatastack-docker/src/dkan-opendatastack/src/dkan_starter:/var/www/html:nocopy
