version: '2.1'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  elasticsearch-importer-api:
    build: ./src/elasticsearch-import-api-docker
    environment:
      APP_ELASTIC_SERVER_HOST: 'http://elasticsearch:9200'
    ports:
      - "8088:80"
    depends_on:
      - elasticsearch

  dkan-mariadb:
    image: wodby/mariadb:10.2-3.0.1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dkan
      MYSQL_USER: dkan
      MYSQL_PASSWORD: dkan
    healthcheck:
        test: "mysql --user=root --password=password -e 'select 1;'"
        timeout: 3s
        retries: 10

  dkan-memcached:
    image: wodby/memcached:1.4-2.0.0

  dkan-apache-php:
    image: opendatastack/dkan-opendatastack:latest
    environment:
      DB_HOST: dkan-mariadb
      DB_DRIVER: mysql
      DB_USER: dkan
      DB_PASSWORD: dkan
      DB_NAME: dkan
      MEMCACHED_HOST: dkan_memcached
    depends_on:
      dkan-mariadb:
        condition: service_healthy
    ports:
      - "80:80"
